lb config \
--distribution trixie \
-a amd64 \
--apt-recommends true \
--chroot-squashfs-compression-type zstd \
--mirror-chroot-security https://security.debian.org/debian-security/ \
--mirror-binary https://deb.debian.org/debian/ \
--mirror-bootstrap https://deb.debian.org/debian/ \
--initsystem systemd \
--image-name LIKEALINUX_0 \
--memtest memtest86+ \
--uefi-secure-boot auto \
--updates true \
--firmware-chroot true \
--linux-flavours "amd64" \
--archive-areas "main contrib non-free" \
--archive-areas "main contrib non-free non-free-firmware" \
--bootloaders "grub-efi" \
--uefi-secure-boot auto \
--iso-application "KazumaKiryus" \
--iso-publisher "pbk123461" \
--iso-volume "LIKEALINUX_0"\
--binary-images iso-hybrid \
--swap-file-size 4096 \
--system live \
--bootappend-live "quiet splash" \
--hdd-label "Dojima" \
--build-with-chroot true